create or replace function ADD_SALESPERSON(_SALESPERSON_ID INTEGER, _FIRST_NAME VARCHAR, _LAST_NAME VARCHAR)
returns VOID
as $MAIN$
begin 
	insert into SALESTEAM(SALESPERSON_ID, FIRST_NAME, LAST_NAME)
	values(_SALESPERSON_ID, _FIRST_NAME, _LAST_NAME);
end;
$MAIN$
language plpgsql;

create or replace function ADD_CAR(_CAR_ID INTEGER, _CAR_MODEL VARCHAR, _CAR_MAKE VARCHAR, _CAR_YEAR INTEGER, _CAR_SERIAL INTEGER)
returns VOID
as $MAIN$
begin 
	insert into CAR(CAR_ID, CAR_MODEL, CAR_MAKE, CAR_YEAR, CAR_SERIAL)
	VALUES(_CAR_ID, _CAR_MODEL, _CAR_MAKE, _CAR_YEAR, _CAR_SERIAL);
end;
$MAIN$
language plpgsql;

select ADD_SALESPERSON(1, 'Louis', 'Green');
select ADD_SALESPERSON(2, 'Mae', 'Neal');

select ADD_CAR(1, 'Acord', 'Honda', 2001, 1234);
select ADD_CAR(2, 'Miata', 'Mazda',1998, 1235);

insert into CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, BILLING_INFO)
VALUES(1, 'Morgan', 'Raine', '1234-1234-1234-1234 444 01/24');
insert into CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, BILLING_INFO)
VALUES(2, 'Jake', 'Thomas', '2468-2468-2468-2468 456 01/25');
insert into CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, BILLING_INFO)
VALUES(3, 'Stacy', 'Flowers', '9999-9999-9999-9999 292 01/24');

insert into INVOICES(INVOICE_ID, INVOICE_DATE, INVOICE_AMOUNT, CAR_ID, SALESPERSON_ID, CUSTOMER_ID)
VALUES(1, CURRENT_DATE, 10000.00, 1, 2, 3);
insert into INVOICES(INVOICE_ID, INVOICE_DATE, INVOICE_AMOUNT, CAR_ID, SALESPERSON_ID, CUSTOMER_ID)
VALUES(2, CURRENT_DATE, 100000.00, 2, 1, 1 );

insert into CARPARTS(PARTS_ID, PART_TYPE, PART_AMOUNT)
VALUES(1, 'Engine', 5000.00);
insert into CARPARTS(PARTS_ID, PART_TYPE, PART_AMOUNT)
VALUES(2, 'Break Pads', 50.00);
insert into CARPARTS(PARTS_ID, PART_TYPE, PART_AMOUNT)
VALUES(3, 'Tail Light', 40.00);

insert into MECHANICS(MECHANIC_ID, FIRST_NAME, LAST_NAME)
VALUES(1, 'Megan', 'Smith');

insert into SERVICETICKETS(SERVICE_TICKET_ID, SERVICE_TOTAL, PARTS_ID, CUSTOMER_ID, CAR_ID, MECHANIC_ID)
VALUES(1, 6000.00, 1,1,2,1);
